kind: configuration
priors:
  amplitude order: 0
  chirp mass:
    maximum: 96.67976382167427
    minimum: 26.700411297080883
    type: UniformInComponentsChirpMass
  dec:
    type: Sine
  luminosity distance:
    alpha: 2
    maximum: 10000
    minimum: 100
    type: PowerLaw
  mass 1:
    maximum: 1000
    minimum: 1
    type: Constraint
  mass 2:
    maximum: 1000
    minimum: 1
    type: Constraint
  mass ratio:
    maximum: 1.0
    minimum: 0.05
    type: UniformInComponentsMassRatio
  phase:
    boundary: periodic
    type: Uniform
  phi 12:
    type: Uniform
  phi jl:
    type: Uniform
  psi:
    type: Uniform
  ra:
    type: Uniform
  spin 1:
    maximum: 1
    minimum: 0
    type: Uniform
  spin 2:
    maximum: 1
    minimum: 0
    type: Uniform
  theta jn:
    type: Sine
  tilt 1:
    type: Sine
  tilt 2:
    type: Sine
